
export const CITIES = [
    { value: '1', viewValue: 'Yopal' },
    { value: '2', viewValue: 'San Andres' },
    { value: '3', viewValue: 'Sonson' },
    { value: '4', viewValue: 'Sogamoso' },
    { value: '5', viewValue: 'Barrancabermeja' },
    { value: '6', viewValue: 'Girardot' },
    { value: '7', viewValue: 'Campoalegre' },
    { value: '8', viewValue: 'Tuquerres' },
    { value: '9', viewValue: 'Mocoa' },
    { value: '10', viewValue: 'Cartago' },
    { value: '11', viewValue: 'Soledad' },
    { value: '12', viewValue: 'Sabanalarga' },
    { value: '13', viewValue: 'Arjona' },
    { value: '14', viewValue: 'Magangue' },
    { value: '15', viewValue: 'Valledupar' },
    { value: '16', viewValue: 'San Jose del Guaviare' },
    { value: '17', viewValue: 'Puerto Lopez' },
    { value: '18', viewValue: 'Yarumal' },
    { value: '19', viewValue: 'Puerto Berrio' },
    { value: '20', viewValue: 'Turbo' },
    { value: '21', viewValue: 'Tunja' },
    { value: '22', viewValue: 'Chiquinquira' },
    { value: '23', viewValue: 'Duitama' },
    { value: '24', viewValue: 'Ayapel' },
    { value: '25', viewValue: 'Lorica' },
    { value: '26', viewValue: 'Socorro' },
    { value: '27', viewValue: 'Riohacha' },
    { value: '28', viewValue: 'Armenia' },
    { value: '29', viewValue: 'Pereira' },
    { value: '30', viewValue: 'Honda' },
    { value: '31', viewValue: 'San Vicente del Caguan' },
    { value: '32', viewValue: 'Florencia' },
    { value: '33', viewValue: 'Guapi' },
    { value: '34', viewValue: 'Neiva' },
    { value: '35', viewValue: 'Garzon' },
    { value: '36', viewValue: 'Ipiales' },
    { value: '37', viewValue: 'Buenaventura' },
    { value: '38', viewValue: 'Tulua' },
    { value: '39', viewValue: 'El Carmen de Bolivar' },
    { value: '40', viewValue: 'Jurado' },
    { value: '41', viewValue: 'Nuqui' },
    { value: '42', viewValue: 'Quibdo' },
    { value: '43', viewValue: 'El Banco' },
    { value: '44', viewValue: 'Cienaga' },
    { value: '45', viewValue: 'Sincelejo' },
    { value: '46', viewValue: 'Tolu' },
    { value: '47', viewValue: 'Arauca' },
    { value: '48', viewValue: 'Tame' },
    { value: '49', viewValue: 'Pamplona' },
    { value: '50', viewValue: 'Ocana' },
    { value: '51', viewValue: 'Orocue' },
    { value: '52', viewValue: 'Obando' },
    { value: '53', viewValue: 'San Martin' },
    { value: '54', viewValue: 'Puerto Carreno' },
    { value: '55', viewValue: 'Bello' },
    { value: '56', viewValue: 'Monteria' },
    { value: '57', viewValue: 'Bucaramanga' },
    { value: '58', viewValue: 'Ibague' },
    { value: '59', viewValue: 'Popayan' },
    { value: '60', viewValue: 'Santa Marta' },
    { value: '61', viewValue: 'Cucuta' },
    { value: '62', viewValue: 'Villavicencio' },
    { value: '63', viewValue: 'Tumaco' },
    { value: '64', viewValue: 'Manizales' },
    { value: '65', viewValue: 'Pasto' },
    { value: '66', viewValue: 'Barranquilla' },
    { value: '67', viewValue: 'Cartagena' },
    { value: '68', viewValue: 'Mitu' },
    { value: '69', viewValue: 'Leticia' },
    { value: '70', viewValue: 'Medellin' },
    { value: '71', viewValue: 'Cali' },
    { value: '72', viewValue: 'Bogota' }
  ];
